### ISSUE TITLE
接入实体鼠标时，隐藏实体鼠标指针，控制启动器内虚拟鼠标

### ISSUE THREAD

**Issue by 10086H** [HopiHopy/PojavZH#20]
### 功能描述

希望添加 Java21 运行环境
使用[Cleanroom](https://github.com/CleanroomMC/Cleanroom?tab=readme-ov-file)需要

使用外置键鼠的时候调用的是手机系统的鼠标而不是游戏(启动器)的虚拟鼠标，希望添加切换按钮让玩家可以自己选择使用手机系统鼠标或者启动器的虚拟鼠标，或者直接调用启动器的虚拟鼠标而不是手机系统的

在低版本(1.12.2)中使用外置键鼠在类似于 jei 搜索栏或者创造模式搜索栏中输入 e 时并不会在搜索栏输入 e 而是直接退出，但相同的问题在 1.16.5 并没有出现

非常感谢你制作了这么优秀的魔改

**Comment by HopiHopy** [comment]
- Jre 21之后会添加的
- 虚拟鼠标一直都没有改过，只是默认启用虚拟鼠标，你可以在设置里关闭它
![IMG_20240413_010247.jpg](https://github.com/HopiHopy/PojavZH/assets/123115192/9078fd06-d7e8-4ed7-948c-26cbc1c52e7a)
- 在低版本中按E会优先输入E而不是关闭UI，这只是MC低版本的输入实现问题，与启动器无关，你可以尝试按ESC关闭（正常来说不都是ESC关闭吗）

**Comment by 10086H** [comment]
如图
![Screenshot_2024-04-13-03-38-31-180_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZH/assets/119060402/e8e4d6da-bf04-478b-8969-14bbef9af13f)
在我连接外置实体键盘鼠标的时候 pojav 使用的手机系统的鼠标，而不是启动器的虚拟鼠标，而 fcl 启动器在连接外置的实体鼠标键盘的时候使用的是启动器的虚拟鼠标
具体[pojavZH 与 fcl 对比](https://www.123pan.com/s/G9J6Vv-lJHnd.html)
issue 并不能上传大于 10m 的视频所以使用网盘
感谢你的回复

**Comment by HopiHopy** [comment]
@10086H Jre21已添加

**Comment by HopiHopy** [comment]
@10086H 至于你说的虚拟鼠标，我最近一直有在尝试制作，但是都失败了🧐🧐🧐
问题我先留着，以后有机会了再来继续尝试制作！

**Comment by xiaofen6666435** [comment]
添加一个可以自定义游戏目录的功能
就像这样![Screenshot_2024_0503_121754_com.tungsten.fcl.png](https://github.com/HopiHopy/PojavZH/assets/145161950/ae76812d-7e07-4d1b-b973-d9c761518dd2)
