### ISSUE TITLE
[BUG] 翻譯問題

### ISSUE THREAD

**Issue by MeowKing** [HopiHopy/PojavZH#25]
### 问题描述

在「繁體中文（台灣）」中，
「界面」應為「介面」
「自定義」應為「自訂」
「手柄」應為「手把」（非標準）或「控制器」
「設置」應為「設定」
「列表」應為「清單」
「運行」應為「執行」
「內存」應為「記憶體」
「布局」應為佈局（部分地方已為「佈局」）
「關於PojavZH」中一處「程序」應為「程式」（順帶一提，‘傳染性’這裡單引號應該改為雙引號「」，簡體中文也應該是雙引號吧）

### 日志/截图或视频

![Screenshot_20240427-144634](https://github.com/HopiHopy/PojavZH/assets/41140156/7f20ed65-b368-4914-9045-bb6a2925655c)

### 复现步骤

```markdown
1.打開啟動器
```

### 预期行为

看到正確的翻譯

### 其他信息

```markdown
- CPU 架构：arm64
- PojavZH 版本：1.0.6.3
```

**Comment by HopiHopy** [comment]
感謝你的反饋，我已經修正了這些內容。如果翻譯還有哪裡不恰當的話，歡迎你继续反饋給我唷！
