### ISSUE TITLE
[BUG] 试图在空对象引用上调用虚拟方法

### ISSUE THREAD

**Issue by ctf7ksy** [HopiHopy/PojavZH#27]
### 问题描述

在启动游戏时启动失败，弹出"试图在空对象引用上调用虚拟方法"的错误提示
（之前一直都可以正常启动，但自上次更新（几天前）后就启动不了了。没有改任何配置和文件）

### 日志/截图或视频

![Screenshot_20240430_115713_net kdt pojavlaunch zh debug](https://github.com/HopiHopy/PojavZH/assets/158819280/dca66c94-97e3-4573-a9e4-0ff12ab89f76)

https://github.com/HopiHopy/PojavZH/assets/158819280/7f7d7922-c5b0-49c5-878a-d5058252a05c

### 复现步骤

```markdown
1，打开启动器
2，下载版本
3，启动游戏
```

### 预期行为

无法正常启动游戏。

### 其他信息

```markdown
- 设备型号：HUAWEI BTK-W00
- CPU 架构：
- Android 版本：12
- PojavZH 版本：1.0.7（9939458）（debug）
```

**Comment by HopiHopy** [comment]
@ctf7ksy 感谢你的反馈，当前问题已经修复：
https://github.com/HopiHopy/PojavZH/releases/tag/9940088
