### ISSUE TITLE
基岩版触控手势

### ISSUE THREAD

**Issue by tytrtetw** [HopiHopy/PojavZH#35]
### 功能描述

在pojav游玩中  一直习惯不了pojav触屏    很烦恼    有时候你长按着只是控制屏幕，但触发到了那个长按导致破坏方块   所以希望作者考虑可不可以增加一个 fcl中的基岩版触控手势  希望能增加一个这个

### 其他信息

![Screenshot_2024_0504_160801](https://github.com/HopiHopy/PojavZH/assets/135793578/821e9e08-8206-4dda-aa8c-ef955334cc66)

**Comment by HopiHopy** [comment]
@tytrtetw 只需要开启这两项设置：
![IMG_20240504_162249.jpg](https://github.com/HopiHopy/PojavZH/assets/123115192/507d65d2-acc8-4bca-a501-048cac3af34f)
