### ISSUE TITLE
打开游戏出现启动器崩溃消息

### ISSUE THREAD

**Issue by PumpkinOrca** [HopiHopy/PojavZH#36]
### 问题描述

更新到最新版本时出现崩溃

### 日志/截图或视频

![Screenshot_2024-05-14-22-20-57-909_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZH/assets/151600265/2c513bbc-11c5-446e-a905-0af888cec737)

### 复现步骤

```markdown
1.Pojav ZH从1.0.8.1更新至1.0.9
2.打开启动器
3.出现崩溃
```

### 预期行为

*

### 其他信息

```markdown
- 设备型号：23046PNC9C
- CPU 架构：Mediatek Dimensity 8200
- Android 版本：14
- PojavZH 版本：1.0.9
```

**Comment by HopiHopy** [comment]
@PumpkinOrca 
正在尝试修复这个问题，你可以帮助测试吗？我没有安卓14的设备：
https://github.com/HopiHopy/PojavZH/actions/runs/9082953748/artifacts/1501936721

**Comment by HopiHopy** [comment]
@

> @PumpkinOrca 正在尝试修复这个问题，你可以帮助测试吗？我没有安卓14的设备： https://github.com/HopiHopy/PojavZH/actions/runs/9082953748/artifacts/1501936721

@PumpkinOrca 不用了不用了，我已经找到合适的安卓14模拟器了，问题也解决了，将在下个小版本修复，实在不好意思，给你带来了不好的体验zzz
