### ISSUE TITLE
[BUG] Fabric1.20.1版本无法进入

### ISSUE THREAD

**Issue by Star1874zz** [HopiHopy/PojavZH#41]
### 问题描述

Fabric实例1.20.6版本可以进，但是1.20.1版本黑屏

### 日志/截图或视频

![Screenshot_2024-05-29-10-16-30-132_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZH/assets/171108164/310d6bb0-afc4-4eae-acb1-e149ff0788c9)
![Screenshot_2024-05-29-10-16-52-842_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZH/assets/171108164/a348d1a1-a9c1-44e7-b161-d61e2bf8a4c5)
![Screenshot_2024-05-29-10-51-58-445_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZH/assets/171108164/9c36274a-1b06-4c45-9ec8-b8b3ccbabcc4)

### 复现步骤

```markdown
启动Fabric1.20.1实例黑屏
```

### 预期行为

.

### 其他信息

```markdown
- 设备型号：Redmi note12turbo
- CPU 架构：骁龙7+Gen2
- Android 版本：13
- PojavZH 版本：1.1.0
```

**Comment by HopiHopy** [comment]
@Star1874zz 请启动你的Fabric1.20.1版本等待一段时间之后，强制退出游戏，然后将你的日志文件上传至此议题

**Comment by Star1874zz** [comment]
[latestlog.txt](https://github.com/HopiHopy/PojavZH/files/15478718/latestlog.txt)

**Comment by HopiHopy** [comment]
这个错误信息表明，在尝试启动Minecraft时，Fabric Loader遇到了一个问题，无法读取某个必要的JAR文件。
具体存在错误的文件：intermediary-1.20.1.jar，因为这个文件是空的或损坏的
请考虑删除该文件重新启动并让Fabric重新下载该文件
文件路径：/storage/emulated/0/Android/data/net.kdt.pojavlaunch.zh/files/.minecraft/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar
