### ISSUE TITLE
建议添加virgl渲染器

### ISSUE THREAD

**Issue by Rogertaf** [HopiHopy/PojavZH#42]
### 功能描述

_zink和另外一个可以开光影的渲染器我用联发科天玑700，720，930尝试打开游戏，结果闪退，更不用说开光影了，我希望能有更多的选择，这个启动器我真的挺喜欢的_

**Comment by Vera-Firefly** [comment]
> ### 功能描述
> _zink和另外一个可以开光影的渲染器我用联发科天玑700，720，930尝试打开游戏，结果闪退，更不用说开光影了，我希望能有更多的选择，这个启动器我真的挺喜欢的_
> 
> ### 其他信息
> _No response_

你是希望使用Mesa21.2.1版本的还是22.0.5?

**Comment by Rogertaf** [comment]
> > ### 功能描述
> > _zink和另外一个可以开光影的渲染器我用联发科天玑700，720，930尝试打开游戏，结果闪退，更不用说开光影了，我希望能有更多的选择，这个启动器我真的挺喜欢的_
> > 
> > ### 其他信息
> > _No response_
> 
> 你是希望使用Mesa21.2.1版本的还是22.0.5?

虽然我不懂，但是听起来好专业

**Comment by Rogertaf** [comment]
> > ### 功能描述
> > _zink和另外一个可以开光影的渲染器我用联发科天玑700，720，930尝试打开游戏，结果闪退，更不用说开光影了，我希望能有更多的选择，这个启动器我真的挺喜欢的_
> > 
> > ### 其他信息
> > _No response_
> 
> 你是希望使用Mesa21.2.1版本的还是22.0.5?

其实都可以啦

**Comment by Vera-Firefly** [comment]
> > > ### 功能描述
> > > _zink和另外一个可以开光影的渲染器我用联发科天玑700，720，930尝试打开游戏，结果闪退，更不用说开光影了，我希望能有更多的选择，这个启动器我真的挺喜欢的_
> > > ### 其他信息
> > > _No response_
> > 
> > 
> > 你是希望使用Mesa21.2.1版本的还是22.0.5?
> 
> 其实都可以啦

那就加Mesa22.0.5的吧

**Comment by Vera-Firefly** [comment]
逝世这个提交吧https://github.com/HopiHopy/PojavZH/actions/runs/9331549996
