### ISSUE TITLE
添加Mesa版本选项(https://github.com/HopiHopy/PojavZH/issues/40)

### ISSUE THREAD

**Issue by LingJHQwQ** [HopiHopy/PojavZH#47]
### 功能描述

用户可以自由的更改Mesa版本，部分处理器因此可以运行Zink。例如我的IQOO Neo8 无法正常运行Mesa24.0.0及26.0.0

**Comment by Vera-Firefly** [comment]
https://github.com/HopiHopy/PojavZH/issues/40
